#!/usr/bin/env python

from OMG import lib_omg as lomg
import numpy as np

nemo_gridfile='/Volumes/P1/Data/GLORYS/data/GL2V1_mesh_mask_new.nc'
nemo_datadir = '/Volumes/P1/Data/GLORYS/data/'
plotdir='/Volumes/P4/workdir/raphael/anims/'

listfiles = []
for nn in np.arange(0,2):
	listfiles.append(nemo_datadir + 'GL2V1_mesh_mask_new.nc' )

nemo = lomg.gearth_anim(nemo_gridfile,plotdir,model='NEMO')
nemo.create_animation(listfiles,'bathy.kmz',showing='bathy_nemo')
